// app/[locale]/(pages)/auth/login/page.tsx
"use client";

import React, { useEffect, useState } from "react";
import { Lock, Mail } from "lucide-react";
import { Discord } from "react-bootstrap-icons";

const LoginPage = () => {
  const [dateTime, setDateTime] = useState<Date | null>(null);

  useEffect(() => {
    const timer = setInterval(() => {
      setDateTime(new Date());
    }, 1000);

    return () => clearInterval(timer);
  }, []);

  const formatDate = (date: Date) => {
    return date.toLocaleDateString("pt-BR", {
      weekday: "long",
      day: "2-digit",
      month: "2-digit",
      year: "numeric",
    });
  };

  const formatTime = (date: Date) => {
    return date.toLocaleTimeString("pt-BR", {
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    });
  };

  return (
    <div
      className="flex justify-between items-start h-screen bg-cover bg-center"
      style={{ backgroundImage: 'url("/bg-login.png")' }} 
    >
      <div className="w-1/2 flex flex-col items-center justify-center text-white mt-32 p-10">
        <h1 className="text-5xl font-bold">
          Bem vindo(a) ao <br />
          <span className="text-6xl">KANDARAKU</span>
        </h1>
        <p className="mt-6 text-lg text-center max-w-md">
          Obrigatoriamente, pedimos que entre no site logado em sua conta. Para ter acesso ao site
          você precisa ter uma conta registrada.
        </p>
        <div className="absolute bottom-16 left-8 text-xl">
          {dateTime && (
            <>
              <p className="text-5xl font-bold">{formatTime(dateTime)}</p>
              <p>{formatDate(dateTime)}</p>
            </>
          )}
        </div>
      </div>
      <div className="w-[650px] flex items-center justify-center p-10">
        <div className="bg-neutral-800 text-white rounded-lg shadow-lg p-8 w-full">
          <div className="flex items-center justify-center">
            <img src="/logo.png" alt="Kandaraku" width={32} height={32} className="w-8 h-8 mr-2" />
            <h2 className="text-3xl font-bold text-center text-purple-500">Kandaraku</h2>
          </div>
          <h3 className="text-xl font-medium text-center mb-6">Fazer login</h3>
          <form>
            <div className="mb-4 space-y-3">
              <label htmlFor="email" className="block text-sm font-medium mb-1">
                Nome de usuário ou email:
              </label>
              <div className="relative">
                <input
                  type="email"
                  id="email"
                  className="w-full p-3 border border-purple-600 rounded focus:outline-none focus:ring-2 focus:ring-purple-600"
                  placeholder="Digite seu nome de usuário ou email"
                />
                <Mail className="absolute right-3 top-3 text-white" />
              </div>
            </div>
            <div className="mb-6 space-y-3">
              <label htmlFor="password" className="block text-sm font-medium mb-1">
                Senha de sua conta:
              </label>
              <div className="relative">
                <input
                  type="password"
                  id="password"
                  className="w-full p-3 border border-purple-600 rounded focus:outline-none focus:ring-2 focus:ring-purple-600"
                  placeholder="Digite sua senha"
                />
                <Lock className="absolute right-3 top-3 text-white" />
              </div>
            </div>
            <div className="text-sm mb-6 text-start">
              <a href="#" className="text-blue-400 underline hover:text-blue-500">
                Recuperar senha
              </a>{" "}
              <br />
              Não possui conta?{" "}
              <a href="#" className="text-blue-400 underline hover:text-blue-500">
                Criar conta
              </a>
            </div>
            <button
              type="submit"
              className="w-full mt-5 border-2 border-purple-600 hover:bg-purple-700 text-white font-semibold p-3 rounded-md transition-colors"
            >
              Entrar
            </button>
          </form>
          <div className="mt-10 text-start">
            <p className="text-sm mb-3">Outras formas de login (Recomendado):</p>
            <button className="flex items-center justify-center p-3 group">
              <Discord className="size-5 mr-2 text-white group-hover:text-blue-500 transition duration-300" />
              <span className="ml-2 overflow-hidden text-white opacity-0 transform -translate-x-4 group-hover:opacity-100 group-hover:translate-x-0 transition duration-300">
                Discord
              </span>
            </button>
          </div>
          <footer className="mt-8 text-xs text-center text-gray-500">
            <p>Copyright © Kandaraku Studios 2024</p>
            <p>Todos os direitos reservados</p>
          </footer>
        </div>
      </div>
    </div>
  );
};

export default LoginPage;

// pages/login.vue
<!-- LoginPage.vue -->
<template>
  <div class="login-page">
    <div class="background-image">
      <img src="https://iili.io/JwEEL9p.jpg" alt="Background Image">
    </div>
    <div class="login-container">
      <h1 class="title">KANDARAKU</h1>
      <div class="login-form">
        <h2 class="form-title">Fazer login</h2>
        <input
          type="text"
          placeholder="NOME DE USUÁRIO OU EMAIL"
          v-model="username"
          class="input-field"
        >
        <input
          type="password"
          placeholder="SENHA DE SUA CONTA"
          v-model="password"
          class="input-field"
        >
        <div class="form-links">
          <NuxtLink to="/recover-password" class="link">Esqueceu sua senha?</NuxtLink>
          <NuxtLink to="/register" class="link">Não possui conta?</NuxtLink>
        </div>
        <button class="login-button" @click="login">Entrar</button>
        <div class="other-login">
          <p>Outras formas de login:</p>
          <div class="other-login-icons">
            <img src="https://iili.io/JNj4kn1.png" alt="Discord Icon">
          </div>
          <p class="recommended">(Recomendado)</p>
        </div>
      </div>
    </div>
    <div class="footer">
      <p>Copyright © Kandaraku Studios 2020 - 2024</p>
      <p>Todos os direitos reservados</p>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      username: '',
      password: '',
    }
  },
  methods: {
    login() {
      // Implement your login logic here
      console.log('Username:', this.username)
      console.log('Password:', this.password)
    }
  }
}
</script>

<style scoped>
/* Add your styles here */
/* Estilos Globais */
body {
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 0;
  background-color: #1c1c1c;
  color: #fff;
}

/* Container Principal */
.login-page {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
  position: relative;
}

/* Imagem de Fundo */
.background-image {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: -1;
}

.background-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

/* Container do Login */
.login-container {
  background-color: rgba(0, 0, 0, 0.8);
  padding: 40px;
  border-radius: 10px;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
  max-width: 400px;
  width: 100%;
}

.title {
  font-size: 36px;
  text-align: center;
  margin-bottom: 20px;
  color: #7a00ff;
  text-shadow: 0 0 10px rgba(122, 0, 255, 0.5);
}

/* Formulário de Login */
.login-form {
  display: flex;
  flex-direction: column;
}

.form-title {
  font-size: 24px;
  margin-bottom: 20px;
  text-align: center;
}

.input-field {
  padding: 10px;
  margin-bottom: 20px;
  border: none;
  border-radius: 5px;
  background-color: rgba(255, 255, 255, 0.1);
  color: #fff;
  font-size: 16px;
}

.form-links {
  display: flex;
  justify-content: space-between;
  margin-bottom: 20px;
}

.link {
  color: #7a00ff;
  text-decoration: none;
  font-size: 14px;
}

.login-button {
  padding: 10px;
  background-color: #7a00ff;
  color: #fff;
  border: none;
  border-radius: 5px;
  font-size: 16px;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.login-button:hover {
  background-color: #6200cc;
}

.other-login {
  margin-top: 20px;
  text-align: center;
}

.other-login-icons img {
  width: 40px;
  height: 40px;
  margin: 10px;
}

.recommended {
  font-size: 12px;
  color: #999;
}

/* Rodapé */
.footer {
  position: absolute;
  bottom: 20px;
  left: 50%;
  transform: translateX(-50%);
  text-align: center;
  font-size: 12px;
  color: #999;
}
</style>
